name: Deploy Vue App to GitHub Pages

on:
  push:
    branches:
      - development  # Run checks on development branch
      - main         # Deploy only when merged into main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint --if-present

      - name: Run tests
        run: npm run test:unit --if-present

      - name: Build project
        run: npm run build
        env:
          NODE_ENV: production
          VUE_APP_REPO_PATH: portfolio
          VUE_APP_BASE_URL: https://yashmahadev.github.io/portfolio

  deploy:
    if: github.ref == 'refs/heads/main'  # Deploy only on main branch
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Vue CLI (Globally)
        run: npm install -g @vue/cli

      - name: Build project
        run: npx vue-cli-service build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./dist
