name: Portfolio Pipeline

on:
  push:
    branches:
      - development  # Run checks on development branch
      - main         # Deploy only when merged into main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
      VUE_APP_BASE_URL: "https://yashmahadev.github.io/portfolio"
      VUE_APP_REPO_PATH: "portfolio"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Vue CLI (Globally)
        run: npm install -g @vue/cli

      - name: Run Tests
        run: npm run test # Ensure you have test scripts in package.json

      - name: Build project
        run: npm run build

  deploy:
    if: github.ref == 'refs/heads/main'  # Deploy only on main branch
    needs: build-and-test
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
      VUE_APP_BASE_URL: "https://yashmahadev.github.io/portfolio"
      VUE_APP_REPO_PATH: "portfolio"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Vue CLI (Globally)
        run: npm install -g @vue/cli

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./dist
